version: "3.9"

services:
  app:
    image: operation-service:local
    container_name: os-app
    ports:
      - "10002:10002"
    depends_on:
      - postgresql
    networks:
      - os

  postgresql:
    image: postgres:14-alpine
    container_name: os-psql
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=finances_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./app/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - os

networks:
  os: